' **************************************************
' Custom code for SalesOrderForm
' Created: 3/1/2012 10:19:28 AM
' **************************************************
Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Windows.Forms
Imports Microsoft.VisualBasic
Imports Epicor.Mfg.BO
Imports Epicor.Mfg.Core
Imports Epicor.Mfg.UI
Imports Epicor.Mfg.UI.Adapters
Imports Epicor.Mfg.UI.Customization
Imports Epicor.Mfg.UI.ExtendedProps
Imports Epicor.Mfg.UI.FormFunctions
Imports Epicor.Mfg.UI.FrameWork
Imports Epicor.Mfg.UI.Searches

Public Class Script

	' ** Wizard Insert Location - Do Not Remove 'Begin/End Wizard Added Module Level Variables' Comments! **
	' Begin Wizard Added Module Level Variables **

	Private WithEvents edvOrderDtl As EpiDataView
	' End Wizard Added Module Level Variables **

	' Add Custom Module Level Variables Here **

	Public Sub InitializeCustomCode()
		' ** Wizard Insert Location - Do not delete 'Begin/End Wizard Added Variable Initialization' lines **
		' Begin Wizard Added Variable Initialization

		'AddHandler Me.OrderRel_Column.ColumnChanged, AddressOf Me.OrderRel_AfterFieldChange
		AddHandler Me.OrderDtl_Column.ColumnChanged, AddressOf Me.OrderDtl_AfterFieldChange
		Me.edvOrderDtl = CType(Me.oTrans.EpiDataViews("OrderDtl"),EpiDataView)
		AddHandler Me.edvOrderDtl.EpiViewNotification, AddressOf Me.edvOrderDtl_EpiViewNotification
		' End Wizard Added Variable Initialization

		' Begin Wizard Added Custom Method Calls


		CreateRowRuleOrderRelDate15Equals_Constant_NullValue()
		CreateRowRuleOrderRelShortChar09Equals_LessThan23Days()
		AddHandler Me.btnRUN.Click, AddressOf Me.btnRUN_Click
		AddHandler Me.epiClear.Click, AddressOf Me.epiClear_Click
		' End Wizard Added Custom Method Calls
	End Sub

	Public Sub DestroyCustomCode()
		' ** Wizard Insert Location - Do not delete 'Begin/End Wizard Added Object Disposal' lines **
		' Begin Wizard Added Object Disposal

		'RemoveHandler Me.OrderRel_Column.ColumnChanged, AddressOf Me.OrderRel_AfterFieldChange
		RemoveHandler Me.OrderDtl_Column.ColumnChanged, AddressOf Me.OrderDtl_AfterFieldChange
		RemoveHandler Me.edvOrderDtl.EpiViewNotification, AddressOf Me.edvOrderDtl_EpiViewNotification
		Me.edvOrderDtl = Nothing
		RemoveHandler Me.btnRUN.Click, AddressOf Me.btnRUN_Click
		RemoveHandler Me.epiClear.Click, AddressOf Me.epiClear_Click
		' End Wizard Added Object Disposal

		' Begin Custom Code Disposal

		' End Custom Code Disposal
	End Sub



	Private Function OrderRelDate15ConstantNullValue_CustomRuleCondition(ByVal args As Epicor.Mfg.UI.ExtendedProps.RowRuleDelegateArgs) As Boolean
		Dim result As Boolean = false
		' ** RowRuleDelegateArgs Properties: args.Arg1, args.Arg2, args.Context, args.Row
		' ** put Row Rule condition evaluation logic here

		Return result
	End Function

	
	Private Sub CreateRowRuleOrderRelDate15Equals_Constant_NullValue()
		' Description: PromiseDate
		' **** begin autogenerated code ****
		Dim warningOrderRel_Date15 As RuleAction = RuleAction.AddControlSettings(Me.oTrans, "OrderRel.Date15", SettingStyle.Warning)
		Dim ruleActions() As RuleAction = New RuleAction() {warningOrderRel_Date15}
		' Create RowRule and add to the EpiDataView.
		Dim rrCreateRowRuleOrderRelDate15Equals_Constant_NullValue As RowRule = New RowRule("OrderRel.Date15", RuleCondition.Equals, "Constant: NullValue", ruleActions)
		CType(Me.oTrans.EpiDataViews("OrderRel"),EpiDataView).AddRowRule(rrCreateRowRuleOrderRelDate15Equals_Constant_NullValue)
		' **** end autogenerated code ****
	End Sub


	Private Sub CreateRowRuleOrderRelShortChar09Equals_LessThan23Days()
		' Description: LTL Error
		' **** begin autogenerated code ****
		Dim errorOrderRel_ShortChar09 As RuleAction = RuleAction.AddControlSettings(Me.oTrans, "OrderRel.ShortChar09", SettingStyle.Error)
		Dim ruleActions() As RuleAction = New RuleAction() {errorOrderRel_ShortChar09}
		' Create RowRule and add to the EpiDataView.
		Dim rrCreateRowRuleOrderRelShortChar09Equals_LessThan23Days As RowRule = New RowRule("OrderRel.ShortChar09", RuleCondition.Equals, "Less Than 23 Days", ruleActions)
		CType(Me.oTrans.EpiDataViews("OrderRel"),EpiDataView).AddRowRule(rrCreateRowRuleOrderRelShortChar09Equals_LessThan23Days)
		' **** end autogenerated code ****
	End Sub

	Private Sub GetPartRevProject()
		dim PartNum as string = edvOrderDtl.dataView(edvOrderDtl.Row)("PartNum"), _
			RevNum as string = edvOrderDtl.dataView(edvOrderDtl.Row)("RevisionNum"), _
			altMethod as string = string.Empty, _
			DrawingNumber as string = string.Empty
'		MessageBox.Show("1")
		dim x as PartRevSearchAdapter = new PartRevSearchAdapter(SalesOrderForm)
		x.BOConnect()
		try
'		MessageBox.Show("2")
		x.GetByID(PartNum, RevNum, AltMethod)
'		MessageBox.Show("3")
		DrawingNumber = x.PartRevSearchData.Tables("PartRev").Rows(0)("DrawNum")
		catch
		end try
		x.Dispose()
'		MessageBox.Show("4")
		x = nothing
		if DrawingNumber <> string.Empty then
'		MessageBox.Show("5")
			dim y as ProjectAdapter = new ProjectAdapter(SalesOrderForm)
'		MessageBox.Show("6")
			y.BOConnect()
			try
'		MessageBox.Show("7")
			y.GetByID(DrawingNumber)
			if y.ProjectData.Tables("Project").Rows(0)("ActiveProject") then
'		MessageBox.Show("8")
				edvOrderDtl.dataView(edvOrderDtl.Row)("ProjectID") = DrawingNumber
'		MessageBox.Show("9")
			end if
			catch
'		MessageBox.Show("10")
				MessageBox.Show(string.Format("Unable to enter a project ID of '{0}' because the project does not exist", DrawingNumber))
			end try
'		MessageBox.Show("11")
			y.Dispose()
			y = nothing
		end if
'		MessageBox.Show("12")
	end sub


	Private Sub OrderDtl_AfterFieldChange(ByVal sender As Object, ByVal args As DataColumnChangeEventArgs)
		' ** Argument Properties and Uses **
		' args.Row("FieldName")
		' args.Column, args.ProposedValue, args.Row
		' Add Event Handler Code
		Select Case args.Column.ColumnName

			Case "RevisionNum"
				GetPartRevProject()
				FAI_BOX()
			Case "PartNum"
				GetPartRevProject()
				FAI_BOX()
			MessageBox.Show("OPTIon2")

		End Select
	End Sub
	dim xPartNum = string.Empty
	Private Sub edvOrderDtl_EpiViewNotification(ByVal view As EpiDataView, ByVal args As EpiNotifyArgs)
		' ** Argument Properties and Uses **
		' view.dataView(args.Row)("FieldName")
		' args.Row, args.Column, args.Sender, args.NotifyType
		' NotifyType.Initialize, NotifyType.AddRow, NotifyType.DeleteRow, NotifyType.InitLastView, NotifyType.InitAndResetTreeNodes
		If (args.NotifyType = EpiTransaction.NotifyType.Initialize) Then
			If (args.Row > -1) Then
				if(xPartNum = "Reset") then return
				epiFAIGrid.DataSource = nothing
				MessageBox.Show("Reset")
				xPartNum = "Reset"
			End If
		End If
	End Sub

Private Sub btnRUN_Click(ByVal sender As Object, ByVal args As System.EventArgs)
	
		FAI_BOX()
		'MessageBox.Show("BUTTON")
	End Sub
Private Sub FAI_BOX
		oTrans.PushStatusText("1", true)
		' ** Place Event Handling Code Here **
		Dim PartNum as string = edvOrderDtl.dataView(edvOrderDtl.Row)("PartNum")
		xPartNum = edvOrderDtl.dataView(edvOrderDtl.Row)("PartNum")
		Dim d As New DynamicQueryAdapter(SalesOrderForm)
		Dim queryResults as DataTable
		d.BOConnect()
		d.GetByID("CIC68322-FAI-Part")
		Dim ds As Epicor.Mfg.BO.QueryExecutionDataSet = d.GetQueryExecutionParameters(d.QueryDesignData)
		Dim r As DataRow = ds.Tables("ExecutionParameter").NewRow()
		r("ParameterName") = "PartNum"
		r("ParameterValue") = PartNum
		oTrans.PushStatusText(PartNum, False)
		r("ValueType") = "integer"
		r("IsEmpty") = False
		r("RowIdent") = String.Empty
		r("RowMod") = "A"
		oTrans.PushStatusText("2", true)
		ds.Tables("ExecutionParameter").Rows.Add(r)
		oTrans.PushStatusText("3", true)
		Dim resultFieldList As String = String.Empty
		Dim topNRecords As Integer = 0
		Dim hasMoreRecords As Boolean
		oTrans.PushStatusText("4", true)
		d.ExecuteByIDParametrized("CIC68322-FAI-Part", ds, "", topNRecords, hasMoreRecords)
		oTrans.PushStatusText("5", true)
		epiFAIGrid.DataSource = d.QueryResults
		oTrans.PushStatusText("6", true)
		SetGrid(epiFAIGrid)
		d.Dispose()
		d = Nothing

	End Sub


Private Sub SetGrid(epiFAIGrid As Epicor.Mfg.UI.FrameWork.EpiUltraGrid)
	Dim msg As [String] = ""

	For Each col As Infragistics.Win.UltraWinGrid.UltraGridColumn In epiFAIGrid.DisplayLayout.Bands(0).Columns
		'			msg = msg + col.Key + " / " + col.Header.Caption + "\r\n";
		col.Hidden = True
	Next

	'MessageBox.Show(msg);

	epiFAIGrid.DisplayLayout.Bands(0).Columns("PartPlant.CheckBox05").Hidden = False
	'epiFAIGrid.DisplayLayout.Bands(0).Columns("PartPlant.Plant").Hidden = True
	epiFAIGrid.DisplayLayout.Bands(0).Columns("PartPlant.Character05").Hidden = False
	epiFAIGrid.DisplayLayout.Bands(0).Columns("PartPlant.Date05").Hidden = False
	epiFAIGrid.DisplayLayout.Bands(0).Columns("P1").Hidden = False
	
	epiFAIGrid.DisplayLayout.Bands(0).Columns("PartPlant.CheckBox05").Header.Caption = "REQ"
	epiFAIGrid.DisplayLayout.Bands(0).Columns("P1").Header.Caption = "Plant"
	epiFAIGrid.DisplayLayout.Bands(0).Columns("PartPlant.Character05").Header.Caption = "REV"
	epiFAIGrid.DisplayLayout.Bands(0).Columns("PartPlant.Date05").Header.Caption = "Date"


	End Sub

	Private Sub epiClear_Click(ByVal sender As Object, ByVal args As System.EventArgs)
		' ** Place Event Handling Code Here **


	epiFAIGrid.DataSource = NOTHING
	epiFAIGrid.Refresh()
'	epiFAIGrid.ResetDisplayLayout() 
'	epiFAIGrid.Layouts.Clear() 

	End Sub
End Class




